/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as SuitesRouteImport } from './routes/suites'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as EquipmentSetsRouteImport } from './routes/equipment-sets'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsIndexRouteImport } from './routes/tests.index'
import { Route as SuitesIndexRouteImport } from './routes/suites.index'
import { Route as RoutesIndexRouteImport } from './routes/routes.index'
import { Route as EquipmentSetsIndexRouteImport } from './routes/equipment-sets.index'
import { Route as TestsTestIdRouteImport } from './routes/tests.$testId'
import { Route as SuitesEditorRouteImport } from './routes/suites.editor'
import { Route as SuitesDefinitionsRouteImport } from './routes/suites.definitions'
import { Route as SuitesSuiteIdRouteImport } from './routes/suites.$suiteId'
import { Route as RoutesEditorRouteImport } from './routes/routes.editor'
import { Route as EquipmentSetsEditorRouteImport } from './routes/equipment-sets.editor'

const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const SuitesRoute = SuitesRouteImport.update({
  id: '/suites',
  path: '/suites',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentSetsRoute = EquipmentSetsRouteImport.update({
  id: '/equipment-sets',
  path: '/equipment-sets',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestsRoute,
} as any)
const SuitesIndexRoute = SuitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuitesRoute,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoutesRoute,
} as any)
const EquipmentSetsIndexRoute = EquipmentSetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EquipmentSetsRoute,
} as any)
const TestsTestIdRoute = TestsTestIdRouteImport.update({
  id: '/$testId',
  path: '/$testId',
  getParentRoute: () => TestsRoute,
} as any)
const SuitesEditorRoute = SuitesEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => SuitesRoute,
} as any)
const SuitesDefinitionsRoute = SuitesDefinitionsRouteImport.update({
  id: '/definitions',
  path: '/definitions',
  getParentRoute: () => SuitesRoute,
} as any)
const SuitesSuiteIdRoute = SuitesSuiteIdRouteImport.update({
  id: '/$suiteId',
  path: '/$suiteId',
  getParentRoute: () => SuitesRoute,
} as any)
const RoutesEditorRoute = RoutesEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => RoutesRoute,
} as any)
const EquipmentSetsEditorRoute = EquipmentSetsEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => EquipmentSetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/equipment-sets': typeof EquipmentSetsRouteWithChildren
  '/routes': typeof RoutesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/suites': typeof SuitesRouteWithChildren
  '/tests': typeof TestsRouteWithChildren
  '/equipment-sets/editor': typeof EquipmentSetsEditorRoute
  '/routes/editor': typeof RoutesEditorRoute
  '/suites/$suiteId': typeof SuitesSuiteIdRoute
  '/suites/definitions': typeof SuitesDefinitionsRoute
  '/suites/editor': typeof SuitesEditorRoute
  '/tests/$testId': typeof TestsTestIdRoute
  '/equipment-sets/': typeof EquipmentSetsIndexRoute
  '/routes/': typeof RoutesIndexRoute
  '/suites/': typeof SuitesIndexRoute
  '/tests/': typeof TestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/settings': typeof SettingsRoute
  '/equipment-sets/editor': typeof EquipmentSetsEditorRoute
  '/routes/editor': typeof RoutesEditorRoute
  '/suites/$suiteId': typeof SuitesSuiteIdRoute
  '/suites/definitions': typeof SuitesDefinitionsRoute
  '/suites/editor': typeof SuitesEditorRoute
  '/tests/$testId': typeof TestsTestIdRoute
  '/equipment-sets': typeof EquipmentSetsIndexRoute
  '/routes': typeof RoutesIndexRoute
  '/suites': typeof SuitesIndexRoute
  '/tests': typeof TestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/equipment-sets': typeof EquipmentSetsRouteWithChildren
  '/routes': typeof RoutesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/suites': typeof SuitesRouteWithChildren
  '/tests': typeof TestsRouteWithChildren
  '/equipment-sets/editor': typeof EquipmentSetsEditorRoute
  '/routes/editor': typeof RoutesEditorRoute
  '/suites/$suiteId': typeof SuitesSuiteIdRoute
  '/suites/definitions': typeof SuitesDefinitionsRoute
  '/suites/editor': typeof SuitesEditorRoute
  '/tests/$testId': typeof TestsTestIdRoute
  '/equipment-sets/': typeof EquipmentSetsIndexRoute
  '/routes/': typeof RoutesIndexRoute
  '/suites/': typeof SuitesIndexRoute
  '/tests/': typeof TestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customScript.js'
    | '/equipment-sets'
    | '/routes'
    | '/settings'
    | '/suites'
    | '/tests'
    | '/equipment-sets/editor'
    | '/routes/editor'
    | '/suites/$suiteId'
    | '/suites/definitions'
    | '/suites/editor'
    | '/tests/$testId'
    | '/equipment-sets/'
    | '/routes/'
    | '/suites/'
    | '/tests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customScript.js'
    | '/settings'
    | '/equipment-sets/editor'
    | '/routes/editor'
    | '/suites/$suiteId'
    | '/suites/definitions'
    | '/suites/editor'
    | '/tests/$testId'
    | '/equipment-sets'
    | '/routes'
    | '/suites'
    | '/tests'
  id:
    | '__root__'
    | '/'
    | '/customScript.js'
    | '/equipment-sets'
    | '/routes'
    | '/settings'
    | '/suites'
    | '/tests'
    | '/equipment-sets/editor'
    | '/routes/editor'
    | '/suites/$suiteId'
    | '/suites/definitions'
    | '/suites/editor'
    | '/tests/$testId'
    | '/equipment-sets/'
    | '/routes/'
    | '/suites/'
    | '/tests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  EquipmentSetsRoute: typeof EquipmentSetsRouteWithChildren
  RoutesRoute: typeof RoutesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SuitesRoute: typeof SuitesRouteWithChildren
  TestsRoute: typeof TestsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suites': {
      id: '/suites'
      path: '/suites'
      fullPath: '/suites'
      preLoaderRoute: typeof SuitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment-sets': {
      id: '/equipment-sets'
      path: '/equipment-sets'
      fullPath: '/equipment-sets'
      preLoaderRoute: typeof EquipmentSetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof TestsRoute
    }
    '/suites/': {
      id: '/suites/'
      path: '/'
      fullPath: '/suites/'
      preLoaderRoute: typeof SuitesIndexRouteImport
      parentRoute: typeof SuitesRoute
    }
    '/routes/': {
      id: '/routes/'
      path: '/'
      fullPath: '/routes/'
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof RoutesRoute
    }
    '/equipment-sets/': {
      id: '/equipment-sets/'
      path: '/'
      fullPath: '/equipment-sets/'
      preLoaderRoute: typeof EquipmentSetsIndexRouteImport
      parentRoute: typeof EquipmentSetsRoute
    }
    '/tests/$testId': {
      id: '/tests/$testId'
      path: '/$testId'
      fullPath: '/tests/$testId'
      preLoaderRoute: typeof TestsTestIdRouteImport
      parentRoute: typeof TestsRoute
    }
    '/suites/editor': {
      id: '/suites/editor'
      path: '/editor'
      fullPath: '/suites/editor'
      preLoaderRoute: typeof SuitesEditorRouteImport
      parentRoute: typeof SuitesRoute
    }
    '/suites/definitions': {
      id: '/suites/definitions'
      path: '/definitions'
      fullPath: '/suites/definitions'
      preLoaderRoute: typeof SuitesDefinitionsRouteImport
      parentRoute: typeof SuitesRoute
    }
    '/suites/$suiteId': {
      id: '/suites/$suiteId'
      path: '/$suiteId'
      fullPath: '/suites/$suiteId'
      preLoaderRoute: typeof SuitesSuiteIdRouteImport
      parentRoute: typeof SuitesRoute
    }
    '/routes/editor': {
      id: '/routes/editor'
      path: '/editor'
      fullPath: '/routes/editor'
      preLoaderRoute: typeof RoutesEditorRouteImport
      parentRoute: typeof RoutesRoute
    }
    '/equipment-sets/editor': {
      id: '/equipment-sets/editor'
      path: '/editor'
      fullPath: '/equipment-sets/editor'
      preLoaderRoute: typeof EquipmentSetsEditorRouteImport
      parentRoute: typeof EquipmentSetsRoute
    }
  }
}

interface EquipmentSetsRouteChildren {
  EquipmentSetsEditorRoute: typeof EquipmentSetsEditorRoute
  EquipmentSetsIndexRoute: typeof EquipmentSetsIndexRoute
}

const EquipmentSetsRouteChildren: EquipmentSetsRouteChildren = {
  EquipmentSetsEditorRoute: EquipmentSetsEditorRoute,
  EquipmentSetsIndexRoute: EquipmentSetsIndexRoute,
}

const EquipmentSetsRouteWithChildren = EquipmentSetsRoute._addFileChildren(
  EquipmentSetsRouteChildren,
)

interface RoutesRouteChildren {
  RoutesEditorRoute: typeof RoutesEditorRoute
  RoutesIndexRoute: typeof RoutesIndexRoute
}

const RoutesRouteChildren: RoutesRouteChildren = {
  RoutesEditorRoute: RoutesEditorRoute,
  RoutesIndexRoute: RoutesIndexRoute,
}

const RoutesRouteWithChildren =
  RoutesRoute._addFileChildren(RoutesRouteChildren)

interface SuitesRouteChildren {
  SuitesSuiteIdRoute: typeof SuitesSuiteIdRoute
  SuitesDefinitionsRoute: typeof SuitesDefinitionsRoute
  SuitesEditorRoute: typeof SuitesEditorRoute
  SuitesIndexRoute: typeof SuitesIndexRoute
}

const SuitesRouteChildren: SuitesRouteChildren = {
  SuitesSuiteIdRoute: SuitesSuiteIdRoute,
  SuitesDefinitionsRoute: SuitesDefinitionsRoute,
  SuitesEditorRoute: SuitesEditorRoute,
  SuitesIndexRoute: SuitesIndexRoute,
}

const SuitesRouteWithChildren =
  SuitesRoute._addFileChildren(SuitesRouteChildren)

interface TestsRouteChildren {
  TestsTestIdRoute: typeof TestsTestIdRoute
  TestsIndexRoute: typeof TestsIndexRoute
}

const TestsRouteChildren: TestsRouteChildren = {
  TestsTestIdRoute: TestsTestIdRoute,
  TestsIndexRoute: TestsIndexRoute,
}

const TestsRouteWithChildren = TestsRoute._addFileChildren(TestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  EquipmentSetsRoute: EquipmentSetsRouteWithChildren,
  RoutesRoute: RoutesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SuitesRoute: SuitesRouteWithChildren,
  TestsRoute: TestsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
