/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as SuitesRouteImport } from './routes/suites'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsIndexRouteImport } from './routes/tests.index'
import { Route as SuitesIndexRouteImport } from './routes/suites.index'
import { Route as TestsTestIdRouteImport } from './routes/tests.$testId'
import { Route as SuitesSuiteIdRouteImport } from './routes/suites.$suiteId'

const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const SuitesRoute = SuitesRouteImport.update({
  id: '/suites',
  path: '/suites',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestsRoute,
} as any)
const SuitesIndexRoute = SuitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuitesRoute,
} as any)
const TestsTestIdRoute = TestsTestIdRouteImport.update({
  id: '/$testId',
  path: '/$testId',
  getParentRoute: () => TestsRoute,
} as any)
const SuitesSuiteIdRoute = SuitesSuiteIdRouteImport.update({
  id: '/$suiteId',
  path: '/$suiteId',
  getParentRoute: () => SuitesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/suites': typeof SuitesRouteWithChildren
  '/tests': typeof TestsRouteWithChildren
  '/suites/$suiteId': typeof SuitesSuiteIdRoute
  '/tests/$testId': typeof TestsTestIdRoute
  '/suites/': typeof SuitesIndexRoute
  '/tests/': typeof TestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/suites/$suiteId': typeof SuitesSuiteIdRoute
  '/tests/$testId': typeof TestsTestIdRoute
  '/suites': typeof SuitesIndexRoute
  '/tests': typeof TestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/suites': typeof SuitesRouteWithChildren
  '/tests': typeof TestsRouteWithChildren
  '/suites/$suiteId': typeof SuitesSuiteIdRoute
  '/tests/$testId': typeof TestsTestIdRoute
  '/suites/': typeof SuitesIndexRoute
  '/tests/': typeof TestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customScript.js'
    | '/suites'
    | '/tests'
    | '/suites/$suiteId'
    | '/tests/$testId'
    | '/suites/'
    | '/tests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customScript.js'
    | '/suites/$suiteId'
    | '/tests/$testId'
    | '/suites'
    | '/tests'
  id:
    | '__root__'
    | '/'
    | '/customScript.js'
    | '/suites'
    | '/tests'
    | '/suites/$suiteId'
    | '/tests/$testId'
    | '/suites/'
    | '/tests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  SuitesRoute: typeof SuitesRouteWithChildren
  TestsRoute: typeof TestsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suites': {
      id: '/suites'
      path: '/suites'
      fullPath: '/suites'
      preLoaderRoute: typeof SuitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof TestsRoute
    }
    '/suites/': {
      id: '/suites/'
      path: '/'
      fullPath: '/suites/'
      preLoaderRoute: typeof SuitesIndexRouteImport
      parentRoute: typeof SuitesRoute
    }
    '/tests/$testId': {
      id: '/tests/$testId'
      path: '/$testId'
      fullPath: '/tests/$testId'
      preLoaderRoute: typeof TestsTestIdRouteImport
      parentRoute: typeof TestsRoute
    }
    '/suites/$suiteId': {
      id: '/suites/$suiteId'
      path: '/$suiteId'
      fullPath: '/suites/$suiteId'
      preLoaderRoute: typeof SuitesSuiteIdRouteImport
      parentRoute: typeof SuitesRoute
    }
  }
}

interface SuitesRouteChildren {
  SuitesSuiteIdRoute: typeof SuitesSuiteIdRoute
  SuitesIndexRoute: typeof SuitesIndexRoute
}

const SuitesRouteChildren: SuitesRouteChildren = {
  SuitesSuiteIdRoute: SuitesSuiteIdRoute,
  SuitesIndexRoute: SuitesIndexRoute,
}

const SuitesRouteWithChildren =
  SuitesRoute._addFileChildren(SuitesRouteChildren)

interface TestsRouteChildren {
  TestsTestIdRoute: typeof TestsTestIdRoute
  TestsIndexRoute: typeof TestsIndexRoute
}

const TestsRouteChildren: TestsRouteChildren = {
  TestsTestIdRoute: TestsTestIdRoute,
  TestsIndexRoute: TestsIndexRoute,
}

const TestsRouteWithChildren = TestsRoute._addFileChildren(TestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  SuitesRoute: SuitesRouteWithChildren,
  TestsRoute: TestsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
